Repository jenkinsci/jobcacher-artifactory-storage-plugin, pull requests merged in 2025-03, with the labels that each got.

#82 Depends on 2.479.3 and remove deprecated methods
  pom.xml
  src/main/java/io/jenkins/plugins/jobcacher/artifactory/ArtifactoryItemPath.java
  src/main/java/io/jenkins/plugins/jobcacher/artifactory/ArtifactoryItemStorage.java
Labels: developer

#83 Remove unused direct deps
  pom.xml
  src/main/java/io/jenkins/plugins/jobcacher/artifactory/ArtifactoryItemStorage.java
Labels: dependencies, chore

#88 Remove jobcacher override
  pom.xml
Labels: chore

#89 Migrate tests to JUnit5
  src/test/java/io/jenkins/plugins/jobcacher/artifactory/ArtifactoryItemPathTest.java
  src/test/java/io/jenkins/plugins/jobcacher/artifactory/ConfigurationAsCodeTest.java
  src/test/java/io/jenkins/plugins/jobcacher/artifactory/DataMigrationTest.java
Labels: tests
